### ISSUE TITLE
player_locale always returns en_US when called in player_login

### ISSUE THREAD

**Issue by justin97530** [PseudoKnight/CHSpigot#3]
When I call player_locale during player_login, it always returns en_US. But calling it in an alias works perfectly. Is this a bug?

I'm using CHSpigot 1.4.0 and git-Spigot-870264a-0a645a2, latest snapshot as of this post.

**Comment by PseudoKnight** [comment]
This sounds normal. It probably defaults to en_US until the client sends the information. Not even the UUID is accessible during the player_join event, which is why I added it into the event. Try delaying one or more ticks.
